#pragma config(Sensor, S1,     rightLight,     sensorColorNxtFULL)
#pragma config(Sensor, S2,     leftLight,      sensorColorNxtFULL)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          aux,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PickleFLLRobotDriver.c"

#include "AlignOnLine.c"
task main() {
	//drive(4200, 100);
//drive(4600,100);
drive(2200, 100);
alignOnLineColor(40);
drive(1400, 100);
//drive(4000, 100);
turn(300, 60);
drive(1000, 60);
alignOnLineColor(-40);
drive(-400, 60);
turn(-350, 60);
drive(800, 60);
//drive(1800, 100)
//alignOnLine(60);
//drive(2000, 60);
	drive(-600, 60);
	turn(210, 60);
	drive(1100, 70);
	turn(200, 60);
	alignOnLineColor(-40);
	drive(200, 60);
	turn(300, 60);
	driveAndAct(60, 0, 0, 0, 10);
	wait1Msec(100);
	driveAndAct(40, 0, 0, 0, 10);
	drive(100, 60);
	turn(-300, 80);
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
	wait1Msec(2000);
	stopMotors();
	drive(-200, 60);
	turn(300, 70);
	drive(-600, 80);
	driveAndAct(90, 0, 0, 0, 10);
	drive(700, 60);
	turn(-300, 70);
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
	wait1Msec(500);
	stopMotors();
	drive(-1000, 100);
	alignOnLineColor(-40);
	drive(100, 40);
	turn(330, 60);
	drive(600, 60);
	motor[motorLeft] = 40;
	motor[motorRight] = 40;
	while(SensorValue[rightLight] != 1);
	stopMotors();
	turn(-100, 40);
	nMotorEncoder[motorAux] = 0;
	while (nMotorEncoder[motorAux] > -100) {
		motor[motorAux] = -30;
	}
	stopMotors();
	//driveAndAct(-100, 0, 0, 0, -30);
	drive(-800, 60);
	driveAndAct(100, 0, 0, 0, 30);

}
