#pragma config(Sensor, S1,     leftLight,      sensorLightActive)
#pragma config(Sensor, S2,     rightLight,     sensorLightActive)
#pragma config(Motor,  motorA,          motorLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorAux,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PickleFLLRobotDriver.c"
#include "AlignOnLine.c"


task main()
{
	drive(-2600, 80);
	turn(-400, 80);
	drive(100, 50);
	wallFollowLeft(-600, 80);
	alignOnLine(100);
	driveAndAct(75, 2400, 2200, 80, 50);
	alignOnLine(100);
	turn(400, -80);
	drive(300, -80);
	turn(400, -80);
	drive(9000, 80);//haha what is that measure even anyway
	//pick up yellow whatsit
	stopMotors();
}
