#pragma config(Sensor, S1,     rightLight,     sensorColorNxtFULL)
#pragma config(Sensor, S2,     leftLight,      sensorColorNxtFULL)
#pragma config(Motor,  motorA,          aux,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PickleFLLRobotDriver.c"

#include "AlignOnLine.c"
task main() {
	drive(-2350, 100);
alignOnLineColor(-40);
drive(-900, 80);
turn(330, 40);
motor[left] = 80;
motor[right] = 80;
wait1Msec(1500);
stopMotors();
drive(-300, 50);
turn(400, 60);
drive(-50, 40);
motor[aux] = -30;
wait1Msec(200);
motor[aux] = 0;

turn(-100, 60);
drive(1000, 70);
turn(50, 80);
drive(1500, 80);
motor[left] = 40;
motor[right] = 40;
wait1Msec(1000);
stopMotors();
motor[aux]=-30;
wait1Msec(1000);
motor[aux] = 0;
//drive(600, 80);
/*alignOnLineColor(-40);
turn(200, 40);
drive(-800, 80);
motor[aux] = -30;
wait1Msec(200);
motor[aux] = 0;
drive(600, 100);
turn(-200, 50);
drive(-800, 80);
turn(-400, 50);
drive(1300, 50);
turn(200, 60);
drive(1000, 50);*/
}
